const express = require('express');
const app = express();
const port = 3000;

// قائمة الكلمات مع التلميحات
const words = [
    
        {"word": "apple", "hint": "A common fruit", "language": "en"},
        {"word": "banana", "hint": "A yellow tropical fruit", "language": "en"},
        {"word": "cat", "hint": "A small domesticated carnivorous mammal", "language": "en"},
        {"word": "dog", "hint": "Man's best friend", "language": "en"},
        {"word": "elephant", "hint": "The largest land animal", "language": "en"},
        {"word": "fish", "hint": "An aquatic animal", "language": "en"},
        {"word": "giraffe", "hint": "A tall animal with a long neck", "language": "en"},
        {"word": "house", "hint": "A place where people live", "language": "en"},
        {"word": "island", "hint": "Land surrounded by water", "language": "en"},
        {"word": "jacket", "hint": "A piece of clothing worn on the upper body", "language": "en"},
        {"word": "kangaroo", "hint": "An Australian marsupial", "language": "en"},
        {"word": "lemon", "hint": "A sour yellow fruit", "language": "en"},
        {"word": "moon", "hint": "The Earth's natural satellite", "language": "en"},
        {"word": "notebook", "hint": "A book of blank pages for writing notes", "language": "en"},
        {"word": "orange", "hint": "A citrus fruit", "language": "en"},
        {"word": "pencil", "hint": "A tool used for writing or drawing", "language": "en"},
        {"word": "quilt", "hint": "A warm bed covering", "language": "en"},
        {"word": "rabbit", "hint": "A small mammal with long ears", "language": "en"},
        {"word": "sun", "hint": "The star at the center of our solar system", "language": "en"},
        {"word": "tree", "hint": "A large plant with a trunk and branches", "language": "en"},
        {"word": "umbrella", "hint": "A device used for protection against rain", "language": "en"},
        {"word": "vase", "hint": "A container used to hold flowers", "language": "en"},
        {"word": "whale", "hint": "The largest mammal", "language": "en"},
        {"word": "xylophone", "hint": "A musical instrument with wooden bars", "language": "en"},
        {"word": "yogurt", "hint": "A dairy product made by fermenting milk", "language": "en"},
        {"word": "zebra", "hint": "An African wild horse with black-and-white stripes", "language": "en"},
        {"word": "airplane", "hint": "A vehicle designed for air travel", "language": "en"},
        {"word": "ball", "hint": "A round object used in games", "language": "en"},
        {"word": "car", "hint": "A road vehicle with an engine, four wheels, and seats", "language": "en"},
        {"word": "door", "hint": "A movable barrier for opening and closing an entrance", "language": "en"},
        {"word": "egg", "hint": "An oval or round object laid by a female bird", "language": "en"},
        {"word": "flower", "hint": "The reproductive structure of a plant", "language": "en"},
        {"word": "guitar", "hint": "A musical instrument with six strings", "language": "en"},
        {"word": "hat", "hint": "A head covering", "language": "en"},
        {"word": "ice", "hint": "Frozen water", "language": "en"},
        {"word": "jelly", "hint": "A sweet, gel-like substance", "language": "en"},
        {"word": "kite", "hint": "A toy that flies in the wind", "language": "en"},
        {"word": "lamp", "hint": "A device that produces light", "language": "en"},
        {"word": "mirror", "hint": "A reflective surface", "language": "en"},
        {"word": "nest", "hint": "A structure built by birds to hold eggs", "language": "en"},
        {"word": "octopus", "hint": "A sea creature with eight arms", "language": "en"},
        {"word": "pen", "hint": "A tool used for writing with ink", "language": "en"},
        {"word": "quartz", "hint": "A hard, crystalline mineral", "language": "en"},
        {"word": "rose", "hint": "A type of flower with thorny stems", "language": "en"},
        {"word": "star", "hint": "A luminous point in the night sky", "language": "en"},
        {"word": "tiger", "hint": "A large wild cat with a striped coat", "language": "en"},
        {"word": "violin", "hint": "A string instrument played with a bow", "language": "en"},
        {"word": "water", "hint": "A colorless, transparent liquid essential for life", "language": "en"},
        {"word": "x-ray", "hint": "A type of radiation used for medical imaging", "language": "en"},
        {"word": "yacht", "hint": "A large boat used for pleasure sailing", "language": "en"},
        {"word": "zoo", "hint": "A facility where animals are kept for public display", "language": "en"},
        {"word": "anchor", "hint": "A heavy object used to moor a vessel", "language": "en"},
        {"word": "beach", "hint": "A sandy shore by the sea", "language": "en"},
        {"word": "candle", "hint": "A stick of wax with a wick that burns to provide light", "language": "en"},
        {"word": "dragon", "hint": "A mythical creature resembling a large reptile", "language": "en"},
        {"word": "engine", "hint": "A machine that converts energy into mechanical force", "language": "en"},
        {"word": "feather", "hint": "A structure forming the plumage of birds", "language": "en"},
        {"word": "glove", "hint": "A covering for the hand", "language": "en"},
        {"word": "hammer", "hint": "A tool with a heavy head used for driving nails", "language": "en"},
        {"word": "insect", "hint": "A small arthropod animal with six legs", "language": "en"},
        {"word": "jungle", "hint": "A dense forest in a tropical region", "language": "en"},
        {"word": "kettle", "hint": "A container used for boiling water", "language": "en"},
        {"word": "leopard", "hint": "A large wild cat with a spotted coat", "language": "en"},
        {"word": "mountain", "hint": "A large natural elevation of the earth's surface", "language": "en"},
        {"word": "needle", "hint": "A small thin tool used for sewing", "language": "en"},
        {"word": "ocean", "hint": "A vast body of salt water", "language": "en"},
        {"word": "piano", "hint": "A large keyboard musical instrument", "language": "en"},
        {"word": "queen", "hint": "A female ruler of a country", "language": "en"},
        {"word": "ring", "hint": "A small circular band worn on a finger", "language": "en"},
        {"word": "sand", "hint": "Small grains of rock found on beaches", "language": "en"},
        {"word": "train", "hint": "A series of connected vehicles that run on rails", "language": "en"},
        {"word": "vulture", "hint": "A large bird of prey", "language": "en"},
        {"word": "whistle", "hint": "A small device that makes a sound when blown", "language": "en"},
        {"word": "xenon", "hint": "A chemical element used in lighting", "language": "en"},
        {"word": "yawn", "hint": "An involuntary opening of the mouth due to tiredness", "language": "en"},
        {"word": "zipper", "hint": "A fastening device with interlocking teeth", "language": "en"},
        {"word": "airport", "hint": "A place where airplanes take off and land", "language": "en"},
        {"word": "bicycle", "hint": "A vehicle with two wheels powered by pedals", "language": "en"},
        {"word": "clock", "hint": "A device used to tell time", "language": "en"},
        {"word": "desert", "hint": "A barren area of land with little rain", "language": "en"},
        {"word": "eleven", "hint": "A number that comes after ten", "language": "en"},
        {"word": "forest", "hint": "A large area covered chiefly with trees", "language": "en"},
        {"word": "gold", "hint": "A precious yellow metal", "language": "en"},
        {"word": "helmet", "hint": "A protective head covering", "language": "en"},
        {"word": "internet", "hint": "A global network connecting millions of computers", "language": "en"},
        {"word": "juice", "hint": "A drink made from the extraction of fruit", "language": "en"},
        {"word": "key", "hint": "A small tool used to open a lock", "language": "en"},
        {"word": "lemonade", "hint": "A sweetened lemon-flavored drink", "language": "en"},
        {"word": "moonlight", "hint": "The light reflected by the moon", "language": "en"},
        {"word": "notebook", "hint": "A book of blank pages for writing notes", "language": "en"},
        {"word": "octagon", "hint": "A shape with eight sides", "language": "en"},
        {"word": "pirate", "hint": "A person who attacks ships at sea", "language": "en"},
        {"word": "quarantine", "hint": "A period of isolation to prevent disease spread", "language": "en"},
        {"word": "rainbow", "hint": "A colorful arc in the sky after rain", "language": "en"},
        {"word": "safari", "hint": "An expedition to observe animals in their natural habitat", "language": "en"},
        {"word": "telephone", "hint": "A device for transmitting voices over distances", "language": "en"},
        {"word": "unicorn", "hint": "A mythical horse with a single horn on its forehead", "language": "en"},
        {"word": "volcano", "hint": "A mountain that erupts with lava", "language": "en"},
        {"word": "window", "hint": "An opening in a wall for light and air", "language": "en"},
        {"word": "xenophobia", "hint": "Fear or hatred of strangers", "language": "en"},
        {"word": "yogurt", "hint": "A dairy product made by fermenting milk", "language": "en"},
        {"word": "zucchini", "hint": "A type of summer squash", "language": "en"},      
        {"word": "تفاحة", "hint": "فاكهة شائعة", "language": "ar"},
        {"word": "موز", "hint": "فاكهة صفراء استوائية", "language": "ar"},
        {"word": "قط", "hint": "حيوان أليف صغير", "language": "ar"},
        {"word": "كلب", "hint": "أفضل صديق للإنسان", "language": "ar"},
        {"word": "فيل", "hint": "أكبر حيوان على الأرض", "language": "ar"},
        {"word": "سمكة", "hint": "حيوان مائي", "language": "ar"},
        {"word": "زرافة", "hint": "حيوان طويل الرقبة", "language": "ar"},
        {"word": "بيت", "hint": "مكان للعيش", "language": "ar"},
        {"word": "جزيرة", "hint": "أرض محاطة بالماء", "language": "ar"},
        {"word": "سترة", "hint": "قطعة من الملابس للجسم العلوي", "language": "ar"},
        {"word": "كنغر", "hint": "حيوان جرابي أسترالي", "language": "ar"},
        {"word": "ليمون", "hint": "فاكهة صفراء حامضة", "language": "ar"},
        {"word": "قمر", "hint": "تابع طبيعي للأرض", "language": "ar"},
        {"word": "دفتر", "hint": "كتاب يحتوي على صفحات فارغة لتدوين الملاحظات", "language": "ar"},
        {"word": "برتقال", "hint": "فاكهة حمضية", "language": "ar"},
        {"word": "قلم رصاص", "hint": "أداة للكتابة أو الرسم", "language": "ar"},
        {"word": "بطانية", "hint": "غطاء دافئ للسرير", "language": "ar"},
        {"word": "أرنب", "hint": "حيوان صغير ذو أذنين طويلتين", "language": "ar"},
        {"word": "شمس", "hint": "النجم الذي يدور حوله كوكب الأرض", "language": "ar"},
        {"word": "شجرة", "hint": "نبات كبير ذو جذع وأغصان", "language": "ar"},
        {"word": "مظلة", "hint": "أداة للحماية من المطر", "language": "ar"},
        {"word": "مزهرية", "hint": "وعاء يستخدم لحفظ الزهور", "language": "ar"},
        {"word": "حوت", "hint": "أكبر الثدييات", "language": "ar"},
        {"word": "إكسيليفون", "hint": "آلة موسيقية لها أشرطة خشبية", "language": "ar"},
        {"word": "زبادي", "hint": "منتج ألبان مصنوع من تخمير الحليب", "language": "ar"},
        {"word": "حمار وحشي", "hint": "حصان بري إفريقي ذو خطوط سوداء وبيضاء", "language": "ar"},
        {"word": "طائرة", "hint": "مركبة مصممة للسفر في الجو", "language": "ar"},
        {"word": "كرة", "hint": "جسم دائري يستخدم في الألعاب", "language": "ar"},
        {"word": "سيارة", "hint": "مركبة تسير على الطرق بمحرك وأربع عجلات", "language": "ar"},
        {"word": "باب", "hint": "حاجز متحرك يستخدم لفتح وإغلاق مدخل", "language": "ar"},
        {"word": "بيضة", "hint": "جسم بيضاوي أو دائري تضعه الطيور", "language": "ar"},
        {"word": "زهرة", "hint": "الجزء التناسلي للنباتات", "language": "ar"},
        {"word": "جيتار", "hint": "آلة موسيقية تحتوي على ستة أوتار", "language": "ar"},
        {"word": "قبعة", "hint": "غطاء للرأس", "language": "ar"},
        {"word": "ثلج", "hint": "ماء متجمد", "language": "ar"},
        {"word": "جيلي", "hint": "مادة حلوة تشبه الهلام", "language": "ar"},
        {"word": "طائرة ورقية", "hint": "لعبة تطير في الرياح", "language": "ar"},
        {"word": "مصباح", "hint": "جهاز ينتج الضوء", "language": "ar"},
        {"word": "مرآة", "hint": "سطح يعكس الصور", "language": "ar"},
        {"word": "عش", "hint": "بنية يبنيها الطيور لاحتواء البيض", "language": "ar"},
        {"word": "أخطبوط", "hint": "كائن بحري له ثمانية أذرع", "language": "ar"},
        {"word": "قلم", "hint": "أداة تستخدم للكتابة بالحبر", "language": "ar"},
        {"word": "كوارتز", "hint": "معدن بلوري صلب", "language": "ar"},
        {"word": "وردة", "hint": "نوع من الأزهار ذات السيقان الشائكة", "language": "ar"},
        {"word": "نجمة", "hint": "جسم مضيء في السماء الليلية", "language": "ar"},
        {"word": "نمر", "hint": "قط بري كبير ذو فرو مخطط", "language": "ar"},
        {"word": "كمان", "hint": "آلة وترية تُعزف بالقوس", "language": "ar"},
        {"word": "ماء", "hint": "سائل عديم اللون وضروري للحياة", "language": "ar"},
        {"word": "أشعة سينية", "hint": "نوع من الإشعاع يستخدم في التصوير الطبي", "language": "ar"},
        {"word": "يخت", "hint": "قارب كبير يستخدم للإبحار الترفيهي", "language": "ar"},
        {"word": "حديقة الحيوان", "hint": "مرفق تُحتجز فيه الحيوانات لعرضها للجمهور", "language": "ar"},
        {"word": "مرساة", "hint": "جسم ثقيل يُستخدم لتثبيت السفينة في مكانها", "language": "ar"},
        {"word": "قوس", "hint": "سلاح يستخدم في إطلاق السهام", "language": "ar"},
        {"word": "سيارة أجرة", "hint": "سيارة تُستخدم لنقل الركاب مقابل أجر", "language": "ar"},
        {"word": "مزمار", "hint": "آلة موسيقية تُنفخ من خلالها", "language": "ar"},
        {"word": "ساحر", "hint": "شخص يُظهر الخدع السحرية", "language": "ar"},
        {"word": "مطر", "hint": "ماء يتساقط من السحب", "language": "ar"},
        {"word": "نهر", "hint": "مجرى مائي طبيعي كبير", "language": "ar"},
        {"word": "أفعى", "hint": "زاحف طويل بلا أرجل", "language": "ar"},
        {"word": "شاحنة", "hint": "مركبة كبيرة لنقل البضائع", "language": "ar"},
        {"word": "مظلة", "hint": "أداة تُستخدم للحماية من الشمس أو المطر", "language": "ar"},
        {"word": "مزهرية", "hint": "وعاء يستخدم لعرض الزهور", "language": "ar"},
        {"word": "حوت", "hint": "أكبر الثدييات البحرية", "language": "ar"},
        {"word": "أكسيليفون", "hint": "آلة موسيقية لها قضبان خشبية", "language": "ar"},
        {"word": "زرافة", "hint": "أطول حيوان بري", "language": "ar"},
        {"word": "حمار", "hint": "حيوان أليف يُستخدم للركوب وحمل الأحمال", "language": "ar"},
        {"word": "حطب", "hint": "خشب يُستخدم كوقود", "language": "ar"},
        {"word": "شجرة نخيل", "hint": "نوع من الأشجار التي تنمو في المناطق الحارة", "language": "ar"},
        {"word": "ساعة", "hint": "جهاز يستخدم لقياس الوقت", "language": "ar"},
        {"word": "سلم", "hint": "أداة تُستخدم للصعود والنزول", "language": "ar"},
        {"word": "قلعة", "hint": "بنية كبيرة كانت تُستخدم في الماضي للدفاع", "language": "ar"},
        {"word": "نظارات", "hint": "عدسات تُستخدم لتحسين الرؤية", "language": "ar"},
        {"word": "ساعة حائط", "hint": "جهاز يستخدم لقياس الوقت ويُعلق على الحائط", "language": "ar"},
        {"word": "فأس", "hint": "أداة تُستخدم لقطع الخشب", "language": "ar"},
        {"word": "نحاس", "hint": "معدن بني محمر", "language": "ar"},
        {"word": "مغناطيس", "hint": "جسم يجذب الحديد", "language": "ar"},
        {"word": "غابة", "hint": "منطقة واسعة مغطاة بالأشجار", "language": "ar"},
        {"word": "مثلث", "hint": "شكل هندسي بثلاثة أضلاع", "language": "ar"},
        {"word": "ممحاة", "hint": "أداة تُستخدم لإزالة الكتابة", "language": "ar"},
        {"word": "قلب", "hint": "عضو يضخ الدم في الجسم", "language": "ar"},
        {"word": "نافذة", "hint": "فتحة في الجدار تسمح بدخول الضوء والهواء", "language": "ar"},
        {"word": "كرسي", "hint": "أثاث يُستخدم للجلوس", "language": "ar"},
        {"word": "مروحة", "hint": "جهاز يستخدم لتبريد الهواء", "language": "ar"},
        {"word": "مقص", "hint": "أداة تستخدم لقص الأشياء", "language": "ar"},
        {"word": "قارب", "hint": "وسيلة نقل على الماء", "language": "ar"},
        {"word": "نقود", "hint": "وسيلة تستخدم لشراء السلع والخدمات", "language": "ar"},
        {"word": "مسرح", "hint": "مكان تُعرض فيه المسرحيات والعروض", "language": "ar"}


    
    
];
// دالة لاختيار كلمة عشوائية
function getRandomWord() {
    const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex];
}

// تقديم API محلي
app.get('/word', (req, res) => {
    const randomIndex = Math.floor(Math.random() * words.length);
    res.json(words[randomIndex]);
});

// نقطة النهاية على المسار الجذر لاختبار الخادم
app.get('/', (req, res) => {
    res.send('Server is running');
});

app.listen(port, () => {
    console.log(`Server running at http://localhost:${port}`);
});